AllCops:
  TargetRubyVersion: 2.6
  DisabledByDefault: true
  SuggestExtensions: false

Style/HashSyntax:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: false

Style/BarePercentLiterals:
  EnforcedStyle: percent_q
  Enabled: true

# EnforcedStyle: empty_lines => 16 offenses
# EnforcedStyle: no_empty_lines => 0 offense
Layout/EmptyLinesAroundBlockBody:
  EnforcedStyle: no_empty_lines
  Enabled: true

Style/MethodDefParentheses:
  EnforcedStyle: require_parentheses
  Enabled: true

Naming/MethodName:
  EnforcedStyle: snake_case
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space
  Enabled: true

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: no_space
  Enabled: true

Naming/VariableName:
  EnforcedStyle: snake_case
  Enabled: true

Style/MissingElse:
  EnforcedStyle: case
  Enabled: true

Lint/Debugger:
  Enabled: true

Layout/DefEndAlignment:
  Enabled: true

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/DuplicateCaseCondition:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/DuplicateHashKey:
  Enabled: true

Lint/ElseLayout:
  Enabled: true

Style/EndBlock:
  Enabled: true

Lint/SuppressedException:
  Enabled: true

Lint/ImplicitStringConcatenation:
  Enabled: true

Lint/MultipleComparison:
  Enabled: true
